model_args:
  device: cuda
  img_size: 1888
  conf_thres: 0.25
  iou_thres: 0.45
  pdf_dpi: 144
  layout_weight: models/Layout/model_final.pth
  mfd_weight: models/MFD/weights.pt
  mfr_weight: models/MFR/UniMERNet
